# Generated by Django 5.1.6 on 2025-02-15 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('video_id', models.CharField(blank=True, max_length=50)),
                ('public_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('duration', models.IntegerField(default=60)),
                ('difficulty_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20)),
                ('target', models.CharField(choices=[('ARMS', 'Arms'), ('BACK', 'Back'), ('CARDIO', 'Cardio'), ('CHEST', 'Chest'), ('CORE', 'Core'), ('LEGS', 'Legs'), ('LOWERBODY', 'Lower Body'), ('SHOULDER', 'Shoulders'), ('SPEEDAGILITY', 'Speed Agility'), ('UPPERBODY', 'Upper Body')], max_length=20)),
                ('public_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sets', models.IntegerField(default=2)),
                ('rest', models.IntegerField(default=120)),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnessApp.workout')),
            ],
        ),
    ]
