# Generated by Django 5.1.6 on 2025-02-24 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='mode',
            field=models.CharField(choices=[('REPS', 'Rep Based'), ('TIME', 'Time Based')], default='REPS', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='WorkoutCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sets', models.IntegerField(default=2)),
                ('set_rest', models.IntegerField(default=120)),
                ('exercise_rest', models.IntegerField(default=30)),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnessApp.workout')),
            ],
        ),
        migrations.CreateModel(
            name='CircuitExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_quantity', models.IntegerField(default=0)),
                ('recommended_weight', models.IntegerField(default=0)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnessApp.exercise')),
                ('circuit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnessApp.workoutcircuit')),
            ],
        ),
        migrations.DeleteModel(
            name='Circuit',
        ),
    ]
