# Generated by Django 5.1.6 on 2025-03-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0002_exercise_mode_exercise_weight_flag_workoutcircuit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='video_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='circuitexercise',
            name='recommended_weight',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='target',
            field=models.CharField(choices=[('ARMS', 'Arms'), ('BACK', 'Back'), ('CARDIO', 'Cardio'), ('CHEST', 'Chest'), ('CORE', 'Core'), ('LEGS', 'Legs'), ('LOWERBODY', 'Lower Body'), ('SHOULDER', 'Shoulders'), ('SPEEDAGILITY', 'Speed Agility'), ('UPPERBODY', 'Upper Body'), ('WHOLEBODY', 'Whole Body')], max_length=20),
        ),
    ]
