# Generated by Django 5.1.6 on 2025-04-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0002_workoutsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='status',
            field=models.CharField(choices=[('NOTSTARTED', 'Not Started'), ('INPROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOTSTARTED', max_length=20),
        ),
    ]
