# Generated by Django 5.1.6 on 2025-03-09 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0003_workout_video_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circuitexercise',
            old_name='circuit_id',
            new_name='circuit',
        ),
        migrations.RenameField(
            model_name='circuitexercise',
            old_name='exercise_id',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='workoutcircuit',
            old_name='workout_id',
            new_name='workout',
        ),
    ]
