# Generated by Django 5.1.6 on 2025-04-20 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0004_alter_workoutsession_scheduled_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.IntegerField(default=0)),
                ('rest', models.IntegerField(default=0)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnessApp.workoutcircuit')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnessApp.exercise')),
                ('workoutSession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnessApp.workoutsession')),
            ],
        ),
    ]
