# Generated by Django 5.1.6 on 2025-04-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0005_workoutsessiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsessiondata',
            name='sequence_number',
            field=models.IntegerField(default=0),
        ),
    ]
