# Generated by Django 5.1.6 on 2025-04-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0006_workoutsessiondata_sequence_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutsessiondata',
            options={'ordering': ['sequence_number']},
        ),
    ]
