# Generated by Django 5.1.6 on 2025-04-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0007_alter_workoutsessiondata_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutsessiondata',
            old_name='rest',
            new_name='rest_after',
        ),
        migrations.AddField(
            model_name='workoutsessiondata',
            name='rest_before',
            field=models.IntegerField(default=0),
        ),
    ]
