# Generated by Django 5.1.6 on 2025-04-21 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0008_rename_rest_workoutsessiondata_rest_after_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutSessionData',
            new_name='WorkoutSessionStep',
        ),
    ]
