# Generated by Django 5.1.6 on 2025-04-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0009_rename_workoutsessiondata_workoutsessionstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsessionstep',
            name='first_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutsessionstep',
            name='last_flag',
            field=models.BooleanField(default=False),
        ),
    ]
