# Generated by Django 5.1.6 on 2025-05-18 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0010_workoutsessionstep_first_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsessionstep',
            name='circuit_exercise',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='fitnessApp.circuitexercise'),
            preserve_default=False,
        ),
    ]
