# Generated by Django 5.1.6 on 2025-05-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0011_workoutsessionstep_circuit_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='current_step_sequence',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('COMPLETED', 'Completed')], default='CREATED', max_length=20),
        ),
    ]
