# Generated by Django 5.1.6 on 2025-06-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0012_workoutsession_current_step_sequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='video_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
