# Generated by Django 5.2.1 on 2025-06-09 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitnessApp", "0013_alter_exercise_video_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessappuser",
            name="coach",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fitnessappuser",
            name="coach_flag",
            field=models.BooleanField(default=False),
        ),
    ]
