# Generated by Django 5.1.6 on 2025-06-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0014_fitnessappuser_coach_fitnessappuser_coach_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
