# Generated by Django 5.1.6 on 2025-06-11 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0015_workoutsession_scheduled_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessappuser',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='fitnessappuser',
            name='coach_flag',
        ),
        migrations.RemoveField(
            model_name='fitnessappuser',
            name='dummy',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='user',
        ),
        migrations.CreateModel(
            name='FitnessAppPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=500)),
                ('last_name', models.CharField(blank=True, max_length=500)),
                ('coach_flag', models.BooleanField(default=False)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitnessApp.fitnessappperson')),
            ],
        ),
        migrations.AddField(
            model_name='fitnessappuser',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitnessApp.fitnessappperson'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fitnessApp.fitnessappperson'),
        ),
    ]
