# Generated by Django 5.1.6 on 2025-06-12 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0016_remove_fitnessappuser_coach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessappperson',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fitnessappperson',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessappuser',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='fitnessApp.fitnessappperson'),
        ),
    ]
