# Generated by Django 5.2.1 on 2025-06-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitnessApp", "0018_alter_fitnessappperson_first_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="mode",
        ),
        migrations.AddField(
            model_name="circuitexercise",
            name="mode",
            field=models.CharField(
                choices=[("REPS", "Rep Based"), ("TIME", "Time Based")],
                default="REPS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="circuitexercise",
            name="reps",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="circuitexercise",
            name="time",
            field=models.IntegerField(default=0),
        ),
    ]
