# Generated by Django 5.1.6 on 2025-06-14 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0019_remove_exercise_mode_circuitexercise_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuitexercise',
            name='mode_quantity',
        ),
    ]
