# Generated by Django 5.1.6 on 2025-06-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0020_remove_circuitexercise_mode_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='difficulty_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='INTERMEDIATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='target',
            field=models.CharField(choices=[('ARMS', 'Arms'), ('BACK', 'Back'), ('CARDIO', 'Cardio'), ('CHEST', 'Chest'), ('CORE', 'Core'), ('LEGS', 'Legs'), ('LOWERBODY', 'Lower Body'), ('SHOULDER', 'Shoulders'), ('SPEEDAGILITY', 'Speed Agility'), ('UPPERBODY', 'Upper Body'), ('WHOLEBODY', 'Whole Body')], default='WHOLEBODY', max_length=20),
        ),
    ]
