# Generated by Django 5.2.1 on 2025-07-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitnessApp", "0021_alter_workout_difficulty_level_alter_workout_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutsessionstep",
            name="exercise_number",
            field=models.IntegerField(default=0),
        ),
    ]
