# Generated by Django 5.2.1 on 2025-07-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitnessApp", "0022_workoutsessionstep_exercise_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="circuitexercise",
            name="exercise_rest",
            field=models.IntegerField(default=30),
        ),
    ]
