# Generated by Django 5.2.1 on 2025-07-17 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitnessApp", "0023_circuitexercise_exercise_rest"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fitnessApp.fitnessappperson",
            ),
        ),
        migrations.AddField(
            model_name="workout",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fitnessApp.fitnessappperson",
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="difficulty_level",
            field=models.CharField(
                choices=[
                    ("BEGINNER", "Beginner"),
                    ("INTERMEDIATE", "Intermediate"),
                    ("ADVANCED", "Advanced"),
                    ("UNSPECIFIED", "Unspecified"),
                ],
                default="INTERMEDIATE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="target",
            field=models.CharField(
                choices=[
                    ("ARMS", "Arms"),
                    ("BACK", "Back"),
                    ("CARDIO", "Cardio"),
                    ("CHEST", "Chest"),
                    ("CORE", "Core"),
                    ("LEGS", "Legs"),
                    ("LOWERBODY", "Lower Body"),
                    ("SHOULDER", "Shoulders"),
                    ("SPEEDAGILITY", "Speed Agility"),
                    ("UPPERBODY", "Upper Body"),
                    ("WHOLEBODY", "Whole Body"),
                    ("UNSPECIFIED", "Unspecified"),
                ],
                default="WHOLEBODY",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workoutsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("INPROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                ],
                default="CREATED",
                max_length=20,
            ),
        ),
    ]
