# Generated by Django 5.2.1 on 2025-07-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitnessApp", "0024_exercise_creator_workout_creator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="personalized_flag",
            field=models.BooleanField(default=False),
        ),
    ]
