# Generated by Django 5.2.1 on 2025-07-17 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitnessApp", "0025_workout_personalized_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutsession",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creator",
                to="fitnessApp.fitnessappperson",
            ),
        ),
    ]
