# Generated by Django 5.2.1 on 2025-07-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitnessApp", "0026_workoutsession_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="difficulty_level",
            field=models.CharField(
                choices=[
                    ("BEGINNER", "Beginner"),
                    ("INTERMEDIATE", "Intermediate"),
                    ("ADVANCED", "Advanced"),
                    ("UNSPECIFIED", "Unspecified"),
                ],
                default="UNSPECIFIED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="target",
            field=models.CharField(
                choices=[
                    ("ARMS", "Arms"),
                    ("BACK", "Back"),
                    ("CARDIO", "Cardio"),
                    ("CHEST", "Chest"),
                    ("CORE", "Core"),
                    ("LEGS", "Legs"),
                    ("LOWERBODY", "Lower Body"),
                    ("SHOULDER", "Shoulders"),
                    ("SPEEDAGILITY", "Speed Agility"),
                    ("UPPERBODY", "Upper Body"),
                    ("WHOLEBODY", "Whole Body"),
                    ("UNSPECIFIED", "Unspecified"),
                ],
                default="UNSPECIFIED",
                max_length=20,
            ),
        ),
    ]
