# Generated by Django 5.2.1 on 2025-07-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitnessApp", "0027_alter_workout_difficulty_level_alter_workout_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitnessappperson",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="fitnessappperson",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
