# Generated by Django 5.2.1 on 2025-07-29 01:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitnessApp", "0028_alter_fitnessappperson_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fitnessappuser",
            options={},
        ),
        migrations.AlterModelManagers(
            name="fitnessappuser",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="fitnessappuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="fitnessappuser",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="fitnessappuser",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="fitnessappuser",
            name="username",
        ),
        migrations.AlterField(
            model_name="fitnessappuser",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="fitnessappuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="fitnessappuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
