# Generated by Django 5.2.1 on 2025-07-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitnessApp", "0029_alter_fitnessappuser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessappuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fitnessappuser",
            name="email",
            field=models.EmailField(
                error_messages={
                    "unique": "This email address is already registered. Please use a different one."
                },
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
