# Generated by Django 5.2.1 on 2025-07-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitnessApp", "0030_fitnessappuser_is_staff_alter_fitnessappuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessappperson",
            name="request_coach_flag",
            field=models.BooleanField(default=False),
        ),
    ]
